### PR TITLE
update to the latest core

### PR DESCRIPTION
**Pull request by EricCornelson**
@roblourens Could you double check that the args removed in `terminateSession` and `getReadonlyOrigin` are truly not used anywhere? I couldn't find a single caller that passed them.

### CODE REVIEW

**Comment by roblourens** [comment]
I guess I'm not sure why they were removed here? https://github.com/Microsoft/vscode-chrome-debug-core/commit/8c8f002f2091a6cd7e6750d4c8291ea2dc007251#diff-3f2b49e806f8f5a10250ee3ffff9be31R1651

**Comment by EricCornelson** [comment]
Initially I didn't intend to remove them, but they got caught by a "remove all unused declarations", and when I looked for any callers that passed them I found none, so I left them removed.

**Comment by roblourens** [comment]
But I think we should put them back for node2 right?

**Comment by roblourens** [comment]
I mean put the callers back in -core that were removed by that commit

**Comment by EricCornelson** [comment]
I took another look, and I still don't see any case where the extra params in `terminateSession` are used, but there was a case where `getRemoteOrigin` was used in node before the refactoring, so I'll add that guy back in.

**Comment by roblourens** [comment]
It looks like node still uses the args, and they used to be passed in before https://github.com/microsoft/vscode-chrome-debug-core/commit/8c8f002f2091a6cd7e6750d4c8291ea2dc007251#diff-3f2b49e806f8f5a10250ee3ffff9be31R1316

**Comment by EricCornelson** [comment]
Got it, I'll add them both back in

**Pull request merged**
