### PR TITLE
prevent early exit event for EH debugging

### PR DESCRIPTION
**Pull request by weinand**
for details see Microsoft/vscode#43516

### CODE REVIEW

**Comment by roblourens** [comment]
Don't you need one in the `close` handler too?

**Comment by weinand** [comment]
I thought so too, but (at least on macOS) it was not needed. I'll verify on Windows on linux...

**Comment by roblourens** [comment]
I'm pretty sure listening to both of those is redundant, I should remove 'close'...

**Comment by weinand** [comment]
@roblourens I've just tried the PR on Windows and you were right: you need an "if" in the close handler too.

**Pull request merged**
